// GNOME's unmodified source SVGs remain in ui/assets. The same adaptive
// SVG rendering policy used by utility-icons.slint is also used for status
// symbols: render at logical size for normal/smaller UI scales and increase
// raster resolution only when AppWindow enlarges the scene, capped at 4x.
// Tint is applied to the SVG mask, not by editing the original artwork.
// License: GNOME Project CC-BY-SA-3.0-US; see THIRD_PARTY_NOTICES.md.
import { Theme } from "../theme/theme.slint";

export component SymbolicSvgIcon inherits Rectangle {
    in property <image> artwork;
    in property <float> render-scale: 1.0;
    in property <color> tint: Theme.foreground;
    background: transparent;

    private property <float> internal-render-scale:
        root.render-scale > 1.0
            ? (root.render-scale < 4.0 ? root.render-scale : 4.0)
            : 1.0;

    Image {
        x: 0px;
        y: 0px;
        width: root.width * root.internal-render-scale;
        height: root.height * root.internal-render-scale;
        source: root.artwork;
        image-fit: contain;
        colorize: root.tint;
        transform-origin: { x: 0px, y: 0px };
        transform-scale: 1.0 / root.internal-render-scale;
    }
}

export component ControllerIcon inherits SymbolicSvgIcon {
    artwork: @image-url("../assets/applications-games-symbolic.svg");
}
